# Application
spring.application.name=inventory-saas
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_saas
spring.datasource.username=postgres
spring.datasource.password=0807
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=VGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9ySldUVG9rZW5HZW5lcmF0aW9uQW5kVmFsaWRhdGlvbjIwMjQ=
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
